import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "AutoML Classifier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <div className="flex min-h-screen">
            <SideNav />
            <main className="flex-1 bg-secondary px-20 py-10">{children}</main>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
